Add;

Version 1.x:
    - ./droopescan scan -u drupal.org fails
    - better error for empty file when `scan`
    - SIGINT capture for new scanning.
    - Add "output to file" functionality.
        - resume when -U and "output to file"
    - URL after redirect is not provided?
    - When mass-scanning with CMS provided, it sometimes says cms_name is
          something it's not. Like, when versions: [] is empty true, but now even
          more misleading.
    
    real problems:
        - ConnectionError is dodgy:
            [Mon Jul 20 22:56:33 2015] Line '112.126.68.4   00101.com' raised:
            Traceback (most recent call last):
              File "/root/droopescan/dscan/plugins/internal/scan.py", line 154, in _process_identify_futures
                cms_name, repaired_url = future.result(timeout=opts['timeout_host'])
              File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 396, in result
                return self.__get_result()
              File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 55, in run
                result = self.fn(*self.args, **self.kwargs)
              File "/root/droopescan/dscan/plugins/internal/scan.py", line 139, in _process_cms_identify
                if inst.cms_identify(vf, url, new_opts['timeout'], new_opts['headers']) == True:
              File "/root/droopescan/dscan/plugins/internal/base_plugin_internal.py", line 756, in cms_identify
                headers)
              File "/root/droopescan/dscan/plugins/internal/base_plugin_internal.py", line 674, in enumerate_file_hash
                r = self.session.get(url + file_url, timeout=timeout, headers=headers)
              File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 477, in get
                return self.request('GET', url, **kwargs)
              File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
                resp = self.send(prep, **send_kwargs)
              File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
                r = adapter.send(request, **kwargs)
              File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
                raise ConnectionError(err, request=request)
            ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))

Version 2.x:
    - Break API to remove finds, isempty. Instead, simply return finds.
    - Break API to replace 'interesting urls' key with 'interesting_urls'.
    - Break API to add url (the URL which was requested to be scanned) and final_url which is the URL after redirects.
    - Break API to detect plugin version.
    - Wordpress?

Relevant:
- https://wappalyzer.com/ -
  http://www.opensourcecms.com/general/cms-marketshare.php
0010.idv.tw
0010.info
0010.ru
001081.com
0014d1c9cdd8.click-network.com
00187.it
001bocai.com
157.7.235.109	0010.idv.tw
96.8.117.140	0010.info
37.140.192.125	0010.ru
157.7.184.20	001081.com
131.191.14.148	0014d1c9cdd8.click-network.com
92.222.25.156	00187.it
5.44.233.202	001bocai.com
