Add;

Version 1.x:
    Fix broken build on new debian installs. Dependencies in working state:
        diff /tmp/now /tmp/prev
        50c49
        < responses==0.4.0
        ---
        > responses==0.3.0

        Heh, funny story, my tests started to fail with the same error you mention
        above.

        I put the following line before the setattr of my class decorator:

        <pre>
            print(cls, name, decorator, m, decorator(m))
        </pre>

        (<class 'dscan.tests.base_http_tests.BaseHttpTests'>, 'test_add_slash_to_urls', <bound method RequestsMock.activate of <responses.RequestsMock object at 0xb5b7aa8c>>, <unbound method BaseHttpTests.test_add_slash_to_urls>, <function test_add_slash_to_urls at 0xb5b96144>)
        (<class 'dscan.tests.base_http_tests.BaseHttpTests'>, 'test_add_slash_to_urls', <bound method RequestsMock.activate of <responses.RequestsMock object at 0xb5bcaa6c>>, <unbound method BaseHttpTests.test_add_slash_to_urls>, <unbound method NoneType.test_add_slash_to_urls>)

        This means there's been a modification to the return values of
        responses.activate between responses 0.3.0 and 0.4.0 (last parameter is
        different).

        I think it is due to this:

        https://github.com/getsentry/responses/commit/96d36d1457724823e76367de6b4c69ddd7b7907a?diff=split

    - error-log not working.
        example:
        
            Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/dscan/plugins/internal/base_plugin_internal.py", line 211, in _process_results_multisite
            output = result['future'].result(timeout=timeout_host)
          File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 396, in result
            return self.__get_result()
          File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 55, in run
            result = self.fn(*self.args, **self.kwargs)
          File "/usr/local/lib/python2.7/dist-packages/dscan/plugins/internal/base_plugin_internal.py", line 314, in url_scan
            finds, is_empty = enum['func'](**kwargs)
          File "/usr/local/lib/python2.7/dist-packages/dscan/plugins/internal/base_plugin_internal.py", line 597, in enumerate_version
            hsh = futures[file_url].result()
          File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 403, in result
            return self.__get_result()
          File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 55, in run
            result = self.fn(*self.args, **self.kwargs)
          File "/usr/local/lib/python2.7/dist-packages/dscan/plugins/internal/base_plugin_internal.py", line 634, in enumerate_file_hash
            r = self.session.get(url + file_url, timeout=timeout)
          File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 477, in get
            return self.request('GET', url, **kwargs)
          File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
            resp = self.send(prep, **send_kwargs)
          File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
            r = adapter.send(request, **kwargs)
          File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
            raise ConnectionError(err, request=request)
        ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))

Version 2.x
    - Break API to remove finds, isempty. Instead, simply return finds.
    - Break API to replace 'interesting urls' key with 'interesting_urls'.
    - Break API to add url (the URL which was requested to be scanned) and final_url which is the URL after redirects.
    - Break API to detect plugin version.

Relevant:
- https://wappalyzer.com/ -
  http://www.opensourcecms.com/general/cms-marketshare.php
