Add;

Version 1.x:
    Fix broken build on new debian installs. Dependencies in working state:
        diff /tmp/now /tmp/prev
        26c25
        < futures==3.0.2
        ---
        > futures==2.2.0
        30c29
        < lxml==3.4.0
        ---
        > lxml==3.4.2
        34c33
        < nose==1.3.7
        ---
        > nose==1.3.6
        44c43
        < python-debian==0.1.27
        ---
        > python-debian==0.1.23
        50c49
        < responses==0.4.0
        ---
        > responses==0.3.0

Hello all,

I apologize in advance as it is very likely this is an issue with my project and
not on nose itself. I've been as thorough as I can in my investigation, however.

*The issue:* Instead of each individual test being ran, tests fail with an error
message similar to the following:

<pre>
TypeError: unbound method test_determine_detect_false_ok() must be called with
NoneType instance as first argument (got nothing instead)
</pre>

The location of the stack trace is not present on the errors, but is as follows
(obtained with `--pdb`)

<pre>
 > /usr/lib/python2.7/unittest/case.py(329)run()
 -> testMethod()
</pre>

*Expected result:* Tests are ran successfuly and fail or succeed on their own
merit.

*Steps to reproduce:* I apologize 

    - error-log not working.
        example:
        
            Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/dscan/plugins/internal/base_plugin_internal.py", line 211, in _process_results_multisite
            output = result['future'].result(timeout=timeout_host)
          File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 396, in result
            return self.__get_result()
          File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 55, in run
            result = self.fn(*self.args, **self.kwargs)
          File "/usr/local/lib/python2.7/dist-packages/dscan/plugins/internal/base_plugin_internal.py", line 314, in url_scan
            finds, is_empty = enum['func'](**kwargs)
          File "/usr/local/lib/python2.7/dist-packages/dscan/plugins/internal/base_plugin_internal.py", line 597, in enumerate_version
            hsh = futures[file_url].result()
          File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 403, in result
            return self.__get_result()
          File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 55, in run
            result = self.fn(*self.args, **self.kwargs)
          File "/usr/local/lib/python2.7/dist-packages/dscan/plugins/internal/base_plugin_internal.py", line 634, in enumerate_file_hash
            r = self.session.get(url + file_url, timeout=timeout)
          File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 477, in get
            return self.request('GET', url, **kwargs)
          File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
            resp = self.send(prep, **send_kwargs)
          File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
            r = adapter.send(request, **kwargs)
          File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
            raise ConnectionError(err, request=request)
        ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))

Version 2.x
    - Break API to remove finds, isempty. Instead, simply return finds.
    - Break API to replace 'interesting urls' key with 'interesting_urls'.
    - Break API to add url (the URL which was requested to be scanned) and final_url which is the URL after redirects.
    - Break API to detect plugin version.

Relevant:
- https://wappalyzer.com/ -
  http://www.opensourcecms.com/general/cms-marketshare.php
